// export default {
//     AUTH_SET: 'AUTH_SET',
//     AUTH_REMOVE: 'AUTH_REMOVE',
//     AUTH_START_REFRESH: 'AUTH_START_REFRESH',
//     AUTH_STOP_REFRESH: 'AUTH_STOP_REFRESH',
// }

export const AUTH_SET = 'AUTH_SET'
export const AUTH_REMOVE = 'AUTH_REMOVE'
export const AUTH_START_REFRESH = 'AUTH_START_REFRESH'
export const AUTH_STOP_REFRESH = 'AUTH_STOP_REFRESH'